// Code generated by Wails. DO NOT EDIT.
// This stub is replaced at runtime by the Wails-generated bindings.
// It allows the Vite build to succeed before `wails generate` is run.

'use strict'

const call = (method, ...args) =>
  window?.go?.main?.App?.[method](...args) ??
  Promise.reject(new Error(`Wails not available (${method})`))

export const AddAsset        = (...a) => call('AddAsset', ...a)
export const BackupNow       = (...a) => call('BackupNow', ...a)
export const DiffSnapshots   = (...a) => call('DiffSnapshots', ...a)
export const FindInSnapshots = (...a) => call('FindInSnapshots', ...a)
export const GetConfig       = (...a) => call('GetConfig', ...a)
export const GetDrillHistory = (...a) => call('GetDrillHistory', ...a)
export const GetKeyStatus    = (...a) => call('GetKeyStatus', ...a)
export const GetSnapshotTree = (...a) => call('GetSnapshotTree', ...a)
export const GetStatus       = (...a) => call('GetStatus', ...a)
export const GetTheme        = (...a) => call('GetTheme', ...a)
export const GetVaultStatus  = (...a) => call('GetVaultStatus', ...a)
export const ListAssets      = (...a) => call('ListAssets', ...a)
export const ListDrives      = (...a) => call('ListDrives', ...a)
export const ListSnapshots   = (...a) => call('ListSnapshots', ...a)
export const MakeColdCopy    = (...a) => call('MakeColdCopy', ...a)
export const RemoveAsset     = (...a) => call('RemoveAsset', ...a)
export const RunDrill        = (...a) => call('RunDrill', ...a)
export const SaveConfig      = (...a) => call('SaveConfig', ...a)
export const SetTheme        = (...a) => call('SetTheme', ...a)
export const SetupVault      = (...a) => call('SetupVault', ...a)
