// Code generated by Wails. DO NOT EDIT.
// This stub is replaced at runtime by the Wails-injected runtime.
// It allows the Vite build to succeed before `wails dev` initialises.

'use strict'

/** Subscribe to a Wails backend event. Returns an unsubscribe function. */
export function EventsOn(event, callback) {
  const runtime = window?.runtime
  if (runtime?.EventsOn) return runtime.EventsOn(event, callback)
  // In browser dev mode without Wails, no-op and return a no-op cleanup.
  return () => {}
}

/** Unsubscribe all listeners for the given event name. */
export function EventsOff(...events) {
  const runtime = window?.runtime
  if (runtime?.EventsOff) return runtime.EventsOff(...events)
}

/** Emit a frontend-side event (rarely needed). */
export function EventsEmit(event, ...data) {
  const runtime = window?.runtime
  if (runtime?.EventsEmit) return runtime.EventsEmit(event, ...data)
}
